---
- name: Add repositories for php and install it
  ansible.builtin.import_role:  
    name: ansible-role-installer
  vars:
    installer_repositories: "{{ php_repositories }}"
    installer_packages: "{{ php_packages }}"

- name: Remove default pool config
  become: true
  ansible.builtin.file:
    path: "{{ php_poold_path }}/www.conf"
    state: absent
  notify: restart php

- name: Copy php config file
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ php_path }}/{{ item | basename }}"
    owner: "{{ php_file_owner }}"
    group: "{{ php_file_group }}"
    mode: "{{ php_file_mode }}"
    force: true
  with_first_found:
    - files:
        - "{{ php_local_config_file }}"
      skip: true
  notify:
    - test configuration
    - restart php

- name: Copy php ini file
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ php_path }}/{{ item | basename }}"
    owner: "{{ php_file_owner }}"
    group: "{{ php_file_group }}"
    mode: "{{ php_file_mode }}"
    force: true
  with_first_found:
    - files:
        - "{{ php_local_phpini_file }}"
      skip: true
  notify:
    - test configuration
    - restart php

- name: Copy php pool.d files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ php_poold_path }}"
    owner: "{{ php_file_owner }}"
    group: "{{ php_file_group }}"
    mode: "{{ php_file_mode }}"
    force: true
  with_fileglob:
    - "{{ php_local_poold_path }}/*.conf"
  notify:
    - test configuration
    - restart php
