---
- name: Add repositories for php and install it
  ansible.builtin.import_role:  
    name: ansible-role-installer
  vars:
    installer_repositories: "{{ php_repositories }}"
    installer_packages: "{{ php_packages }}"

- name: Copy default config
  become: true
  ansible.builtin.copy:
    src: "{{ php_file_path }}/www.conf"
    dest: "{{ php_file_path }}/www.conf.example"
    remote_src: true

- name: Remove default config
  become: true
  ansible.builtin.file:
    path: "{{ php_file_path }}/www.conf"
    state: absent
  notify: restart php

- name: Copy php config files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ php_file_path }}"
    owner: "{{ php_file_owner }}"
    group: "{{ php_file_group }}"
    mode: "{{ php_file_mode }}"
  with_fileglob:
    - "{{ php_local_path }}/*.conf"
  notify: restart php
