---
- name: Ensure that packages are uninstalled
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    autoremove: "{{ php_autoremove }}"
    purge: "{{ php_purge }}"
    state: absent
  loop: "{{ php_packages }}"

- name: Ensure that repositories are uninstalled
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    update_cache: true
    state: absent
  loop: "{{ php_repositories }}"

- name: Remove apt key
  ansible.builtin.import_role:
    name: ansible-role-aptkey
  vars:
    aptkey_name: "{{ php_key_name }}"
    aptkey_path: "{{ php_key_path }}"
    aptkey_uninstall: true
