---
- name: Stop php service
  when: "'php' + php_version + '-fpm' in php_packages"
  become: true
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: stopped

- name: Remove repositories for php and uninstall it
  ansible.builtin.import_role:  
    name: ansible-role-installer
  vars:
    installer_repositories: "{{ php_repositories }}"
    installer_packages: "{{ php_packages }}"
    installer_uninstall: true

- name: Remove apt key
  ansible.builtin.import_role:
    name: ansible-role-aptkey
  vars:
    aptkey_name: php_key_name
    aptkey_path: php_key_path
    aptkey_uninstall: true
